#see https://docs.travis-ci.com/user/languages/python/
language: python
python:
# - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
#  - "3.7"
  - "3.7-dev"
#  - "3.8-dev"
  - "nightly"
install:
  - pip install -qr requirements-dev.txt
  - | # https://github.com/travis-ci/travis-ci/issues/4866
    if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then
      pip install -Iq 'coverage<4.0.0';
    fi
script:
  - coverage run tests.py
after_success:
  coveralls
