#see https://docs.travis-ci.com/user/languages/python/
language: python
python:
# - "2.6"
  - "2.7"
# - "3.2" same message as https://github.com/travis-ci/travis-ci/issues/4866
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
install:
  - pip install -qr requirements-dev.txt
script:
  - coverage run tests.py
after_success:
  coveralls
